// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWF8aBKNOjQod33nDYJ0o0TyQ7qxsYDQ',
    appId: '1:92060340726:web:e40bb368e65fc7a88e77d7',
    messagingSenderId: '92060340726',
    projectId: 'save-drive-d793b',
    authDomain: 'save-drive-d793b.firebaseapp.com',
    storageBucket: 'save-drive-d793b.firebasestorage.app',
    measurementId: 'G-JHX5K1GZNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEB50av8YrmB_KscCYUretbjNFmCXl1CQ',
    appId: '1:92060340726:android:d67be859321b74548e77d7',
    messagingSenderId: '92060340726',
    projectId: 'save-drive-d793b',
    storageBucket: 'save-drive-d793b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8fYW1QqCstzm87KyXoZh3OS_K_zcgwk',
    appId: '1:318640647874:ios:bfe74da6752a5b3d19955b',
    messagingSenderId: '318640647874',
    projectId: 'pbl5thsemester',
    storageBucket: 'pbl5thsemester.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX8fYW1QqCstzm87KyXoZh3OS_K_zcgwk',
    appId: '1:318640647874:ios:bfe74da6752a5b3d19955b',
    messagingSenderId: '318640647874',
    projectId: 'pbl5thsemester',
    storageBucket: 'pbl5thsemester.firebasestorage.app',
    iosBundleId: 'com.example.safeDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWF8aBKNOjQod33nDYJ0o0TyQ7qxsYDQ',
    appId: '1:92060340726:web:3aa226f4f3d712988e77d7',
    messagingSenderId: '92060340726',
    projectId: 'save-drive-d793b',
    authDomain: 'save-drive-d793b.firebaseapp.com',
    storageBucket: 'save-drive-d793b.firebasestorage.app',
    measurementId: 'G-RBRHGB0NKS',
  );

}